apiVersion: v1
kind: Service
metadata:
  name: {{ include "mweb-helm.fullname" . }}
  labels:
    {{- include "mweb-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ include "mweb-helm.fullname" . }}
