apiVersion: apps/v1
kind: Deployment
metadata:
  name: mweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mweb
  template:
    metadata:
      labels:
        app: mweb
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: mweb
        image: mintojoseph/mweb:10
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
